from typing import TypedDict, Optional, Any


class InvestigationState(TypedDict):
    """
    Shared state passed between SentinelAI LangGraph nodes.
    """

    # PostgreSQL
    analysis_run_id: int
    database_context: dict[str, Any]

    # ML / Isolation Forest
    anomaly_results: list[dict[str, Any]]

    # RAG / Vector DB
    retrieved_evidence: list[dict[str, Any]]

    # LangGraph processing
    analysis: Optional[str]
    evaluation: Optional[str]

    # Final result - will be generated by the LLM later
    final_result: Optional[str]